services:
  browser-automation:
    build: .
    ports:
      - "8081:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload 